name: Java CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # запуск вручну

jobs:
  build:
    runs-on: ubuntu-latest    # вибір операційної системи

    steps:
      - name: Checkout project
        uses: actions/checkout@v5   # клонування проекту

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'   # встановлення Java

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn dependency:resolve

      - name: Build project
        run: mvn -B package --file pom.xml   # збірка

      - name: Run tests
        run: mvn test   # запуск юніт-тестів
